### ISSUE TITLE
Provide ADC example

### ISSUE THREAD

**Issue by nkonopinski** [adafruit/Adafruit_ZeroDMA#13]
I'd like to use DMA for collecting audio samples from an analog mic. I tried following a low level example posted here (https://forum.arduino.cc/index.php?topic=346761.0) but I haven't had much success with it. I saw @ladyada mention this library is being used for audio (https://github.com/arduino/ArduinoCore-samd/issues/419). I'm not sure if that's audio from ADC or other means. I'm probably missing something simple but I would love to know how to DMA ADC correctly

**Comment by ladyada** [comment]
hiya, we don't have plans to write an example for ADC, there is some code here that does it
https://github.com/adafruit/Audio/blob/master/input_adcs.cpp

if you figure it out with this library as a shorter example please submit a PR so others will have one too :)
