### ISSUE TITLE
Weak handler alias not working with archived libraries

### ISSUE THREAD

**Issue by Timvrakas** [adafruit/Adafruit_ZeroDMA#14]
I'm building with PlatformIO, so that could be the source of my issues.
This is targeting SAMD51, using Feather M4 Express
Under the normal build configuration, the framework is archived:
`Archiving .pio\build\adafruit_feather_m4\libFrameworkArduino.a`
The first handler is linked in properly, but the others are not. The read channel (0) works, but the write channel fails, ends up hanging at Dummy_Handler.
![image](https://user-images.githubusercontent.com/2514676/75638308-08ffb880-5be0-11ea-9cf7-e17937928862.png)

Which means these directives are not being enacted in Adafruit_ZeroDMA.cpp
```
void DMAC_1_Handler(void) __attribute__((weak, alias("DMAC_0_Handler")));
void DMAC_2_Handler(void) __attribute__((weak, alias("DMAC_0_Handler")));
void DMAC_3_Handler(void) __attribute__((weak, alias("DMAC_0_Handler")));
void DMAC_4_Handler(void) __attribute__((weak, alias("DMAC_0_Handler")));
```

When I run with
`lib_archive = no`
the handlers are populated properly, and everything works as expected.

This might only be an issue with PlatformIO, I can share this over there too, but I would also expect the library to work when archived.

**Comment by ladyada** [comment]
we have this library now 'built' into the BSP, maybe make sure you dont have this library installed separately?

**Comment by Timvrakas** [comment]
I don't think I am. Its building the library that's included in the framework directory.
![image](https://user-images.githubusercontent.com/2514676/75641265-7c0f2c00-5bec-11ea-8368-a0902f0e4de3.png)

**Comment by ladyada** [comment]
not sure then - we only use Arduino IDE

**Comment by Timvrakas** [comment]
On that note, is ZeroDMA SPI currently working? The most recent commit suggests perhaps not. https://github.com/adafruit/ArduinoCore-samd/commit/8b88806d46376d64131f33389f71626052cbe351

**Comment by ladyada** [comment]
should be - we have been using for SPI TFTs - please try arduino IDE

**Comment by Timvrakas** [comment]
Alright. I'll need to get it under the oscilloscope and see what timing changes the DMA introduced. My accelerometer might just be finicky. I'm not planning on dropping my build environment just yet.
