### ISSUE TITLE
Adafruit_ZeroDMA::abort() on SMAD51 clears Trigger and Trigger Action settings

### ISSUE THREAD

**Issue by nikodiyana** [adafruit/Adafruit_ZeroDMA#20]
On SAMD51 (tested with Feather m4) the `abort()` function clears the whole CHCTRLA register:

```
void Adafruit_ZeroDMA::abort(void) {
  ...
#ifdef __SAMD51__
    DMAC->Channel[channel].CHCTRLA.reg = 0; // Disable channel
  ...
}
```
In the same register there are also saved numerous settings. See page 432 of the SAMD51 data sheet.

As a result of a call to abort(), any following Adafruit_ZeroDMA::startJob() call could cause a hang since the whole register is set to 0. For example a trigger source pointing to a SERCOM is now 0.

**Workaround** - instead of abort() use:
`DMAC->Channel[channel].CHCTRLA.bit.ENABLE = 0`

Cheers,
Niko

**Comment by ladyada** [comment]
kk wanna submit a PR that will disable just the ENABLE flag? :)

**Comment by nikodiyana** [comment]
Oks, never done PR before. Let's see...

**Comment by ravedya** [comment]
`wddafefaf`

**Comment by samyk** [comment]
This can be closed per https://github.com/adafruit/Adafruit_ZeroDMA/commit/6211bf31a2d9889eff34dea40b4064624f10b7f8
