### ISSUE TITLE
Linking multiple transfers together

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_ZeroDMA#27]
Hello!

I would like to use DMA SPI to transfer a full 240x240 16bit frame buffer for a TFT screen. 

I think the max transfer count size is 65536, which kind of matches with my testing. It seems although the "count" value is passed to the descriptor as a 32bit value it's expecting a 16bit value. Sending anything larger seems to mask down to 16 bits.  

The datasheet kind of hints at this, and says the max single block transfer is 1 to 256KB, if you were using a 32bit beat size I guess that makes sense. It also hints at using several transfer descriptors linked together, by having one pointing at another. Are there any examples of this? Or can this library handle doing that?

I guess I could try and use SPI as 16bit or 32bit so I can increase the beat size and decrease it's count, but then it seems I'd have to handle telling the sercom how many bytes I actually want to transfer of a 32bit register. I guess I could do that, but I'd rather not. I don't see any benefit, there's already no delay between bytes on the bus already.

Thank you in advance for any advise!

**Comment by ladyada** [comment]
hiya can look at 
https://github.com/adafruit/Adafruit-GFX-Library/blob/f2df85851f51b5d8b3f8be9e78e3c69b19961207/Adafruit_SPITFT.cpp#L1069
best of luck!

**Comment by ghost** [comment]
Apparently all you have to do is add two descriptors, they link automatically. I sure would have appreciated knowing that's all it takes before I went through the trouble of going through all that code.

`  
dma.addDescriptor(
  framebuffer,						// move data from here
  (void *)(&SERCOM2->SPI.DATA.reg), // to here (M4)
  57600,							// this many...
  DMA_BEAT_SIZE_BYTE,               // bytes/hword/words
  true,                             // increment source addr?
  false);                           // increment dest addr?
  
  dma.addDescriptor(
  framebuffer + 57600,				// move data from here
  (void *)(&SERCOM2->SPI.DATA.reg), // to here (M4)
  57600,							// this many...
  DMA_BEAT_SIZE_BYTE,               // bytes/hword/words
  true,                             // increment source addr?
  false);                           // increment dest addr?  
`
