### ISSUE TITLE
compiler.h missing from utility directory

### ISSUE THREAD

**Issue by deadmoo83** [adafruit/Adafruit_ZeroDMA#4]
`\Documents\Arduino\libraries\Adafruit_ZeroDMA/utility/dma.h:319:22: fatal error: compiler.h: No such file or directory`

**Comment by PaintYourDragon** [comment]
Installing Adafruit_ASFcore should take care of this in the interim until a proper patch is devised.

**Comment by PaintYourDragon** [comment]
Adafruit_ASFcore is definitely a prerequisite library. README had been updated appropriately, that'll be the preferred method going forward. Thanks!
