### ISSUE TITLE
SAMD21 SPI slave + DMA

### ISSUE THREAD

**Issue by jrossey** [adafruit/Adafruit_ZeroDMA#7]
Could this library be used when using the SAMD21 as an SPI slave? I have some data that I want to send over SPI using DMA from a SAMD21 slave. 

Would it be possible to make an example for this case?

Thanks!

**Comment by ladyada** [comment]
SPI slave is possible but we don't have example for that, so if you wanted to you could create your own and submit it as a pull requestion! :)
