### ISSUE TITLE
Not included in the Library Manager

### ISSUE THREAD

**Issue by combs** [adafruit/Adafruit_ZeroDMA#9]
Greetings,
this library includes library.properties but doesn't seem to be listed in the main Arduino Library Manager list.

**Comment by ladyada** [comment]
iz here? 
https://www.arduinolibraries.info/libraries/adafruit-zero-dma-library

**Comment by combs** [comment]
Ohhh, ha, I was searching for "ZeroDMA" not "Zero DMA." Thanks!!
